### ISSUE TITLE
dark shell theme / text in activities overview search box too dark

### ISSUE THREAD

**Issue by axelmeunier** [pop-os/gnome-shell-theme#32] opened 2018-05-11 11:24 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution 
Pop!_OS 18.04 LTS
 * Gtk+ 3.0 version
3.22.30-1ubuntu1
 * Desktop environment
Gnome 3.28
 * Pop version 
Version 4.0.0
 ```

**Related Application and/or Shell theming (or name of widget)**
search box in activities overview with pop-dark shell theme

**Actual issue**
The text color is too dark and not readable

**Steps to reproduce**
Install and enable user-theme extension. Switch to pop-dark shell theme with Gnome Tweaks. Open activities overview and write some text in the search box.

**Expected behavior**
Text color should be white/light gray

**Behavior in Adwaita**
I don't know (Adwaita shell theme seems not installed by default). Other themes are fine as far as the color of the text in the activities overview is concerned. 

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment] 2018-05-14 16:28
This issue is a duplicate of #27

**Closed by isantop** 2018-05-14 16:28 UTC
Labels: bug, duplicate
