### ISSUE TITLE
Colors in all drop-down menus of Gnome panel is buggy

### ISSUE THREAD

**Issue by RussianNeuroMancer** [pop-os/gnome-shell-theme#27] opened 2018-05-04 17:09 UTC
```
 * Distribution - Ubuntu 18.04 LTS
 * Gtk+ 3.0 version - 3.22.30-1ubuntu1
 * Desktop environment - Gnome
 * Pop version - Pop!_GNOME+ Version 4.0.0
 ```

**Related Application and/or Shell theming (or name of widget)**

All drop-down menus of Gnome panel 

**Actual issue**

https://github.com/pop-os/gtk-theme/issues/152#issuecomment-385160719

**Comment by Krzbk** [comment] 2018-05-09 04:50
After upgrade to 18.04 on the laptop and desktop, in both cases in drop-down menu a dark font on a dark background, like on screenshot.

**Comment by isantop** [comment] 2018-05-14 16:29
This seems to be caused by a bug in the user-themes extension. If I log into a GNOME session and Switch to the Pop GNOME shell theme (the standard variant), the text is still white.

**Comment by RussianNeuroMancer** [comment] 2018-05-15 07:38
Ok, reported: https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues/73

**Comment by gamunu** [comment] 2018-05-18 06:53
Not sure this is relavent. But I was able to fix this by just replaceing gnome shell theme from last preview release [Pop GTK Version 3.0.0 Beta R4](https://github.com/pop-os/gtk-theme/releases/tag/3.0.0-b4)

**Comment by gamunu** [comment] 2018-05-18 07:02
Not sure this is relevant. But I was able to fix this by just replaceing gnome shell theme from last preview release [Pop GTK Version 3.0.0 Beta R4](https://github.com/pop-os/gtk-theme/releases/tag/3.0.0-b4).
To be clear not the pop-gnome-shell-theme_2.99.4_all.deb but gnome-shell folder reside in each pop gtk shell variant.

**Comment by RussianNeuroMancer** [comment] 2018-07-24 13:06
I find that if I didn't re-enable Pop! theme PPA after upgrade from 17.10 to 18.04 this issue is not present after upgrade and theme remain usable. However, when I enable theme PPA again and update packages - I starting to get this issue?  

@isantop 
Do you sure there is no regression on theme side? 
How this issue is workarounded in Pop! OS images?

**Comment by isantop** [comment] 2018-08-08 19:45
@RussianNeuroMancer This is a fully updated and default-settings installation:

![screenshot from 2018-08-08 13-44-29](https://user-images.githubusercontent.com/5883565/43860542-47847988-9b11-11e8-9b48-2342a38c0378.png)

I think this is being caused by some kind of GNOME Shell issue.

**Comment by RussianNeuroMancer** [comment] 2018-08-10 05:37
@isantop isn't there should be some difference between Pop! OS images and Ubuntu installation with Pop! PPA, that make this issue not reproducible on Pop! OS?

**Comment by RussianNeuroMancer** [comment] 2018-08-22 05:06
Issue is still reproducible on Ubuntu 18.10 with Gnome Shell 3.29.90.

@isantop if possible, could you please look into previous commentary in this bugreport?

**Comment by isantop** [comment] 2018-08-28 20:54
So, after digging into the theming a bit more, I think this can likely be fixed with a patch to the theme. Fix is incoming.

**Closed** 2018-09-04 15:41 UTC
Labels: bug, upstream

**Comment by RussianNeuroMancer** [comment] 2018-09-05 00:07
@isantop Should I close Gnome issue then?

**Comment by isantop** [comment] 2018-09-05 15:18
@RussianNeuroMancer Adwaita still has some issue in the Pop session, so it may not be entirely solved there. This bug just indicates that the Pop theme works correctly in both GNOME and Pop sessions.
