### ISSUE TITLE
The right click drop menu has transparent background ! How to solve this ?

### ISSUE THREAD

**Issue by cata0309** [pop-os/gnome-shell-theme#78] opened 2019-02-10 16:38 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/gnome-shell/theme/pop.css```)
 ```

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Right click background is messed up.

**Steps to reproduce**
Right click on empty desktop.

**Expected behavior**
Show right click menu with white background and black text

**Behavior in POP OS**

Transparent background, very messy and confusing

**Other Note (feature-request, question, etc...)**
A screenshot of the issue

![screenshot from 2019-02-10 12-42-39](https://user-images.githubusercontent.com/35623921/52536424-fb705a00-2d62-11e9-9b8e-61d898f3e695.png)

**Comment by brs17** [comment] 2019-02-10 16:51
This is a duplicate of https://github.com/pop-os/gtk-theme/issues/272. Please continue the conversation there.

**Closed by brs17** 2019-02-10 16:51 UTC
