### ISSUE TITLE
Poweroff text hard to read & username not aligned

### ISSUE THREAD

**Issue by Mancooo** [pop-os/gnome-shell-theme#72] opened 2019-01-17 22:12 UTC
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Fedora release 29 (Twenty Nine)
 * Gtk+ 3.0 version - 3.24.1-1.fc29
 * Desktop environment - Gnome
 * Pop version - Pop!_GNOME+ Version 4.0.2 
 ```

**Related Application and/or Shell theming (or name of widget)**
Pop-dark

**Actual issue**
Poweroff screen text is too dark and hard to read & username in system menu is not aligned properly

**Steps to reproduce**
Try to poweroff & click the system menu (top-right)

**Expected behavior**
Legible text (poweroff screen) and properly aligned username

**Behavior in Adwaita**
No problems

**Other Note (feature-request, question, etc...)**
I am seeing these issues on the latest git
![screenshot from 2019-01-17 23-00-05](https://user-images.githubusercontent.com/12864999/51352257-5ccb4300-1aad-11e9-9231-b3711eb5982c.png)
![screenshot from 2019-01-17 23-01-03](https://user-images.githubusercontent.com/12864999/51352258-5d63d980-1aad-11e9-9105-846cd21eaacb.png)

**Comment by isantop** [comment] 2019-02-07 22:42
I can't seem to replicate this issue with the current version of the theme (4.0.12). Does this issue happen for you if you upgrade to that version of the theme?

**Comment by Mancooo** [comment] 2019-02-08 21:14
Thanks Isantop for looking into this.

I just compiled the latest version, is that from the master_bionic branch?

I have the same issue, this is on Pop Dark. With regular Pop the poweroff text is good, but the username is still not aligned properly. On Pop Dark both things are "messed" up.

![screenshot from 2019-02-08 22-10-39](https://user-images.githubusercontent.com/12864999/52506454-ec689b00-2bee-11e9-9625-06682c9634b5.png)
![screenshot from 2019-02-08 22-10-42](https://user-images.githubusercontent.com/12864999/52506461-effc2200-2bee-11e9-9e84-b0664a69dbbc.png)

**Comment by brs17** [comment] 2019-02-08 23:40
On a fresh install of Pop!_OS, in the dark theme I do see that the highlighted text on the poweroff menu is difficult to read.

The user does not look misaligned though.

**Comment by Mancooo** [comment] 2019-02-09 11:35
I have attached two screengrabs, the first one is from the latest Pop shell theme (dark or light does not matter) and the second is from Adwaita.

You can see the username and icon are not aligned with the Pop theme, with Adwaita they are alright, I know this is very nitpicky...

![screenshot from 2019-02-09 12-29-29](https://user-images.githubusercontent.com/12864999/52520193-29707400-2c67-11e9-9f10-3f2315a0a8cd.png)
![screenshot from 2019-02-09 12-29-44](https://user-images.githubusercontent.com/12864999/52520195-2d9c9180-2c67-11e9-84fd-a31d2141a396.png)

**Comment by isantop** [comment] 2019-03-28 17:25
I'm going to close this as we can't seem to reproduce the alignment issue in the latest theme. The text contrast issue is a duplicate of #59

**Closed by isantop** 2019-03-28 17:25 UTC
Labels: blocked, bug
